version: '3.9'

services:
  db:
    image: postgres:12.12
    container_name: 'my-money-db'
    environment:
      restart: never
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: 'my-money'
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: 'my-money-backend'
    build: .
    command: yarn dev
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - .:/src/app/my-money-backend
      - /src/app/my-money-backend/node_modules
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
